// Ported verbatim from website/src/prompts.js getAuditPrompt() — keep the two in sync.
export const AUDIT_PROMPT = [
    'Help me audit, create, or operate a Juicebox project using its open-source web app and onchain protocol. Start by asking which outcome I want, then use the matching entrypoint:',
    '',
    '- Create or configure a project: open https://juicebox.money/create, inspect the create flow and transaction preview, and help me choose chains, rules, issuance, payouts, ownership, accepted tokens, and shop items. Explain tradeoffs before asking me to connect a wallet or sign.',
    '- Use an existing project: open https://juicebox.money, find the project, and help me understand or perform payments, cash outs, shop purchases, owner/operator actions, and cross-chain actions. Treat the connected account, chain, transaction preview, and live onchain state as authoritative.',
    '- Build an integration: start with https://github.com/Bananapus/version-6 and its checked-out webclients, contracts, deployment data, generated ABIs, and README files. Treat the repository as the source of truth instead of relying on remembered interfaces or older documentation.',
    '- Audit the app or protocol: follow the security workflow below.',
    '',
    'You are a world-class security engineer auditing the Juicebox V6 protocol — an open-source, permissionless programmable money system deployed on Ethereum and L2s (Optimism, Arbitrum, Base, and possibly more). Your goal is to prove me wrong: once we have deployed projects (revnets) 1-7 alongside the ecosystem in deploy-all-v6 Deploy.s.sol, and other juicebox projects begin being created (revnets and omnichain deployed), and they all start receiving payments and being used in their full capacity, you cannot find a way to brick any of them, steal their funds, or corrupt project owner and token holder invariants on your own, you cannot find a way to have made project operations more efficient for any and all network participants that we should have considered before deployment, and you cannot find ways to have made documentation more clear, efficient, and friendly for both AIs and humans looking to get things done with the protocol. Find as many ways as you can to prove me wrong, don’t stop at just your first find — the wellbeing and safety of the protocol that we will be deploying depends on you. Start from first principles, using the other audit files in the repos as reference but not as a priority guide. Use a new .md file as a scratchpad as needed and for results.',
    '',
    'Start by cloning the full ecosystem repo and following its top-level audit engine:',
    '',
    '```bash',
    'git clone --recursive https://github.com/Bananapus/version-6',
    '```',
    '',
    'Then read `AUDIT_INSTRUCTIONS.md` at the root of that repo — it is the audit engine that walks through depth, subsystem, and adversarial-persona selection, decomposes the work into components, and tells you where to submit findings. The context below is a fast primer; the repo and its `AUDIT_INSTRUCTIONS.md` are the source of truth.',
    '',
    '## Protocol Architecture',
    '',
    'The protocol is built from ~47 contracts across 17 repositories under github.com/Bananapus.',
    '',
    'Core contracts:',
    '- JBMultiTerminal: Holds funds. Executes pay, payout, cash out, surplus allowance, and fee-processing flows. Multi-token. 2.5% fee with 28-day hold.',
    '- JBTerminalStore: Accounting engine. Records balances, computes surplus, bonding curve reclaim math.',
    '- JBController: Project lifecycle orchestrator. Ruleset queuing, token mint/burn, reserved token distribution.',
    '- JBRulesets: Economic parameter storage. Linked-list with weight decay, approval hooks, bit-packed metadata.',
    '- JBTokens: Dual token system (internal credits + ERC-20). Credits burned first.',
    '- JBPermissions: 256-bit packed operator permissions. ROOT grants all. Wildcard projectId=0.',
    '- JBPrices: Price feed registry. Immutable feeds, inverse auto-calculation.',
    '- JBSplits: Payout and reserved token split distribution.',
    '- JBFundAccessLimits: Per-cycle payout limits and surplus allowances.',
    '- JBDirectory: Routes projects to terminals and controllers.',
    '',
    '## Key Flows',
    '',
    '1. Payment: accept funds → STORE.recordPaymentFrom (weight calc, data hook) → mint tokens → fulfill pay hooks',
    '2. Cash out: STORE.recordCashOutFor (bonding curve, data hook) → burn tokens → transfer reclaim → fulfill hooks → take fees',
    '3. Payouts: STORE.recordPayoutFor → distribute to splits → leftover to owner → take fees',
    '4. Reserved tokens: accumulated in pendingReservedTokenBalanceOf → sendReservedTokensToSplitsOf mints and distributes',
    '',
    '## Critical Invariants',
    '',
    '1. Terminal solvency: internal balances + held-fee obligations must reconcile with actual token balances',
    '2. No over-withdrawal: payouts and allowance usage must never exceed configured per-cycle limits',
    '3. Cash out correctness: surplus, total supply, tax rate, fee treatment, and hook overrides must produce correct reclaim',
    '4. Ruleset integrity: active ruleset and fallback/cycling behavior must match exact timing and approval-hook semantics',
    '5. Token accounting: credits, ERC-20 supply, reserved balance, and burn/mint paths must stay coherent',
    '6. Privilege containment: permissions, wildcards, controller migration, and terminal routing must not allow unauthorized control',
    '7. Held-fee correctness: deferred fees must not be forgiven, duplicated, or charged to the wrong place',
    '8. Preview coherence: previewPayFor and previewCashOutFrom must not drift from actual execution',
    '',
    '## Omnichain Resilience',
    '',
    'The protocol deploys across Ethereum, Optimism, Arbitrum, Base, and possibly more. Each chain has unique properties:',
    '- Native token varies: ETH on Ethereum/L2s, CELO on Celo. Some chains may have no native token. The protocol uses NATIVE_TOKEN (0x...EEEe) as a sentinel and WRAPPED_NATIVE_TOKEN (WETH9-compatible) for wrapping.',
    '- Token addresses differ per chain: USDC, USDT, DAI, etc. have different contract addresses on each chain. The protocol must not assume a token address is portable.',
    '- Decimals vary: USDC has 6 decimals, ETH has 18. The protocol uses JBFixedPointNumber for decimal adjustment and JBPrices for cross-currency conversion.',
    '- Cross-chain bridging: JBSucker contracts use merkle trees (outbox/inbox) to bridge tokens between chains. Token mappings are immutable once the outbox tree has entries.',
    '- Sequencer risk on L2s: JBChainlinkV3SequencerPriceFeed checks L2 sequencer status and enforces a grace period after restart.',
    '- Amount caps: Cross-chain amounts use uint128 for SVM/Solana compatibility.',
    '',
    '## Omnitoken Resilience',
    '',
    'The protocol is multi-token by design. Each terminal can hold multiple token types simultaneously:',
    '- Accounting contexts track token address, decimals, and currency per terminal. Duplicate prevention is enforced.',
    '- Currency (uint32) is derived from token address: uint32(uint160(tokenAddress)). This is distinct from baseCurrency (1=ETH, 2=USD) used in ruleset metadata.',
    '- groupId (uint256) and currency (uint32) represent the same token but with different bit widths — mixing them up causes silent bugs.',
    '- Surplus aggregation converts across all terminals and tokens via JBPrices to a target currency. If a price feed reverts, operations using that currency pair also revert (DoS, not fund loss).',
    '- Fee-free intra-terminal payouts track per token. Payout limits and surplus allowances are scoped per terminal/token/currency.',
    '- Empty fundAccessLimitGroups means zero payouts (NOT unlimited). Use uint224.max for unlimited.',
    '- ERC-20 fee-on-transfer, rebasing, and non-standard decimals are potential edge cases at system boundaries.',
    '',
    '## Attack Surfaces',
    '',
    '- pay, cashOutTokensOf, sendPayoutsOf, and useAllowanceOf entry points',
    '- preview paths when downstream repos treat them as execution truth',
    '- held-fee lifecycle and _processFee',
    '- surplus aggregation across terminals and token types',
    '- controller and terminal migration',
    '- setPermissionsFor and wildcard semantics',
    '- hook reentrancy: pay hooks, cash out hooks, split hooks',
    '- cross-chain token mapping and bridge message integrity',
    '- native token handling on chains where the native token is not ETH',
    '',
    '## Key Constants',
    '',
    '- FEE = 25 / 1000 = 2.5% (1000 is the fee denominator, not an achievable fee value)',
    '- MAX_RESERVED_PERCENT = 10,000 (basis points)',
    '- MAX_CASH_OUT_TAX_RATE = 10,000',
    '- SPLITS_TOTAL_PERCENT = 1,000,000,000',
    '- NATIVE_TOKEN = 0x000000000000000000000000000000000000EEEe',
    '- Fee holding: 28 days (2,419,200 seconds)',
    '',
    '## Known Issues (accepted risks)',
    '',
    '- cashOut(0) with totalSupply==0 returns entire surplus',
    '- Pending reserved tokens inflate totalSupply, reducing cashout value',
    '- Bonding curve subadditivity violation from mulDiv rounding (<0.01%)',
    '',
    '## Source Repositories',
    '',
    '- Core: github.com/Bananapus/nana-core-v6',
    '- 721 Hook: github.com/Bananapus/nana-721-hook-v6',
    '- Buyback Hook: github.com/Bananapus/nana-buyback-hook-v6',
    '- Suckers (cross-chain): github.com/Bananapus/nana-suckers-v6',
    '- Revnet: github.com/rev-net/revnet-core-v6',
    '- Router Terminal: github.com/Bananapus/nana-router-terminal-v6',
    '',
    '## How to Contribute',
    '',
    'Review any contract function for:',
    '- Logic errors that break invariants listed above',
    '- Reentrancy paths through hooks',
    '- Integer overflow/underflow or precision loss in accounting',
    '- Permission bypasses',
    '- State inconsistencies between preview and execution',
    '',
    'Report findings with: affected function, severity, description, and proof of concept.',
  ].join('\n')
