FROM node:26.7.0-bookworm-slim@sha256:cd565714d4da3e84bfd341e31448f81d47c6362198f152345297c9c1154e6341 AS base

ENV NEXT_TELEMETRY_DISABLED=1 \
    NODE_OPTIONS=--no-experimental-webstorage
WORKDIR /app
RUN npm install --global npm@12.0.1 --no-audit --no-fund

FROM base AS dependencies
COPY package.json package-lock.json .npmrc ./
RUN npm ci --no-audit --no-fund

FROM base AS builder
COPY --from=dependencies /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_BENDYSTRAW_URL
ARG NEXT_PUBLIC_TESTNET_BENDYSTRAW_URL
ARG NEXT_PUBLIC_PARA_API_KEY
ARG NEXT_PUBLIC_PARA_ENV
ARG NEXT_PUBLIC_PARA_ONRAMP_PROVIDER
ARG NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID
ARG NEXT_PUBLIC_VERSION
ARG RAILWAY_GIT_COMMIT_SHA
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL \
    NEXT_PUBLIC_BENDYSTRAW_URL=$NEXT_PUBLIC_BENDYSTRAW_URL \
    NEXT_PUBLIC_TESTNET_BENDYSTRAW_URL=$NEXT_PUBLIC_TESTNET_BENDYSTRAW_URL \
    NEXT_PUBLIC_PARA_API_KEY=$NEXT_PUBLIC_PARA_API_KEY \
    NEXT_PUBLIC_PARA_ENV=$NEXT_PUBLIC_PARA_ENV \
    NEXT_PUBLIC_PARA_ONRAMP_PROVIDER=$NEXT_PUBLIC_PARA_ONRAMP_PROVIDER \
    NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID=$NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID \
    NEXT_PUBLIC_VERSION=${NEXT_PUBLIC_VERSION:-${RAILWAY_GIT_COMMIT_SHA}}
RUN node scripts/check-deployment-env.mjs build && npm run build

FROM base AS runner
ENV NODE_ENV=production \
    HOSTNAME=0.0.0.0 \
    PORT=3000

ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_BENDYSTRAW_URL
ARG NEXT_PUBLIC_TESTNET_BENDYSTRAW_URL
ARG NEXT_PUBLIC_PARA_API_KEY
ARG NEXT_PUBLIC_PARA_ENV
ARG NEXT_PUBLIC_PARA_ONRAMP_PROVIDER
ARG NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID
ARG NEXT_PUBLIC_VERSION
ARG RAILWAY_GIT_COMMIT_SHA
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL \
    NEXT_PUBLIC_BENDYSTRAW_URL=$NEXT_PUBLIC_BENDYSTRAW_URL \
    NEXT_PUBLIC_TESTNET_BENDYSTRAW_URL=$NEXT_PUBLIC_TESTNET_BENDYSTRAW_URL \
    NEXT_PUBLIC_PARA_API_KEY=$NEXT_PUBLIC_PARA_API_KEY \
    NEXT_PUBLIC_PARA_ENV=$NEXT_PUBLIC_PARA_ENV \
    NEXT_PUBLIC_PARA_ONRAMP_PROVIDER=$NEXT_PUBLIC_PARA_ONRAMP_PROVIDER \
    NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID=$NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID \
    NEXT_PUBLIC_VERSION=${NEXT_PUBLIC_VERSION:-${RAILWAY_GIT_COMMIT_SHA}}

COPY --chown=node:node --from=builder /app/public ./public
COPY --chown=node:node --from=builder /app/.next/standalone ./
COPY --chown=node:node --from=builder /app/.next/static ./.next/static
COPY --chown=node:node --from=builder /app/scripts/check-deployment-env.mjs ./scripts/check-deployment-env.mjs
COPY --chown=node:node --from=builder /app/scripts/start-production.mjs ./scripts/start-production.mjs

USER node
EXPOSE 3000
HEALTHCHECK --interval=30s --timeout=5s --start-period=15s --retries=3 CMD node -e "fetch('http://127.0.0.1:'+(process.env.PORT||3000)+'/api/healthz').then(r=>{if(!r.ok)process.exit(1)}).catch(()=>process.exit(1))"
CMD ["node", "scripts/start-production.mjs"]
